### ISSUE TITLE
gets search result for `hair` but not for `hair cut`

### ISSUE THREAD

**Issue by alexjv89** [alexjv89/cashflowy#100]
<img width="1280" alt="pasted_image_19_02_19__11_39_am" src="https://user-images.githubusercontent.com/2733923/52993737-4103e580-343b-11e9-966b-1daae8534726.png">
I get the above when using the key word - `hair` the above results. 

![image](https://user-images.githubusercontent.com/2733923/52993766-5842d300-343b-11e9-81eb-d3cef60bc4d5.png)
I get nothing when using the key word - 'hair cut`

**Comment by aptro** [comment]
Issue with the filter query for list transactions. Fixed.

We are using waterline query ```contains``` to do a text search.
