### ISSUE TITLE
Categories selection in filter transactions limited to top level only

### ISSUE THREAD

**Issue by alexjv89** [alexjv89/cashflowy#26]
Category options are currently this: 
![image](https://user-images.githubusercontent.com/2733923/51021255-0b9bea80-15a7-11e9-97c3-2ab1cb6a32c8.png)

Needs to be similar to this: 
![image](https://user-images.githubusercontent.com/2733923/51021302-28d0b900-15a7-11e9-9ffa-b3cc7778358e.png)

**Comment by aptro** [comment]
fixed. [](https://github.com/alexjv89/cashflowy/commit/1a6ea69546e7a8d15e35edaaeca573de57ec2e39)
