### ISSUE TITLE
List documents UI needs update

### ISSUE THREAD

**Issue by alexjv89** [alexjv89/cashflowy#46]
![image](https://user-images.githubusercontent.com/2733923/51471630-4bc84d80-1d9d-11e9-9e40-88f4685da84d.png)
Above is the current UI for list documents. It has the following problems:
1) It does not tell how many unresolved doubtful transactions are pending manual curation. 
2) It does not tell number of line items extracted
3) It does not show account details and time details.
4) User should be able to define identifiers for the file after uploading the file. For example, user should be able to mark something as statement for the month of June for Acccount xx

**Comment by aptro** [comment]
<img width="1195" alt="screenshot 2019-02-21 at 3 52 27 pm" src="https://user-images.githubusercontent.com/10391409/53161835-c11f7c00-35f0-11e9-8ca8-3c3758646fe9.png">

- [X] how many unresolved doubtful transactions are pending manual curation.
- [X] number of line items extracted
- [X]  account details
- [X] time details
- [X] Ability to add a description for the statement
- [X] Store file in s3
