### ISSUE TITLE
filter: transactions where category or description is empty

### ISSUE THREAD

**Issue by aptro** [alexjv89/cashflowy#80]

**Comment by aptro** [comment]
<img width="373" alt="screenshot 2019-02-21 at 1 52 11 pm" src="https://user-images.githubusercontent.com/10391409/53154228-4b131900-35e0-11e9-9327-ba4804d0baae.png">
* category filter now have a dropdown field -empty- to filter out where its blank.
* writing empty as description will filter out where its blank

**Comment by alexjv89** [comment]
nice !
