### ISSUE TITLE
Auto categorize transactions based on certain criterion

### ISSUE THREAD

**Issue by alexjv89** [alexjv89/cashflowy#98]
This issue is part of #12 

![image](https://user-images.githubusercontent.com/2733923/52992667-6abb0d80-3437-11e9-9ecd-55fd5f07c133.png)

I buy from store fairly often. I dont categorize it as anything but groceries. Having done that more than 100 times, I dont feel like doing that and would rather have that automated. 

Filter criterions: 
1) description is equal to something or contains text.

**Comment by aptro** [comment]
We are using aws machine learning with their multiclass classifier. With initial trials seems decent. With more usage, we can validate and optimize the prediction.

commit: 76b951b
