### ISSUE TITLE
Not able to search based on content in the to field

### ISSUE THREAD

**Issue by alexjv89** [alexjv89/cashflowy#99]
![image](https://user-images.githubusercontent.com/2733923/52993120-04cf8580-3439-11e9-82b4-bcf9be39305e.png)
for something like this, the current search option is to only search by the content in description. As a user I would also want to filter transactions based on the content in the `to` field.

**Comment by aptro** [comment]
<img width="1326" alt="screenshot 2019-02-21 at 2 26 38 pm" src="https://user-images.githubusercontent.com/10391409/53156194-d2fb2200-35e4-11e9-89b4-bd0fcece973d.png">
filter transactions based on the content in the `to` field. (merchant/third party)
